# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(max_length=20)),
                ('question_id', models.IntegerField(max_length=10)),
                ('choice_text', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=200)),
                ('total_count', models.IntegerField(max_length=100)),
            ],
        ),
    ]
