# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='total_count',
            field=models.IntegerField(),
        ),
    ]
