# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20191029_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='question_id',
            field=models.CharField(max_length=200),
        ),
    ]
