# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20191029_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='areaQuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.CharField(max_length=200)),
                ('Choice_text', models.CharField(max_length=200)),
            ],
        ),
    ]
