# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_areaquestiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='allData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField()),
                ('choice_text', models.CharField(max_length=200)),
                ('question_text', models.CharField(max_length=200)),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
