# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_alldata_choice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('choice_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
