# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_timelines_timeline_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelines',
            name='timeline_id',
        ),
    ]
