# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_timelines_timeline_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
